Movie_gid/Movie_gid/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    path('accounts/', include('allauth.urls')),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('contact/', include('contact.urls')),
    path('', include('movies.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Movie_gid/movies/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.MoviesView.as_view(), name='main'),
    path('category/', views.MoviesCategoryView.as_view(), name='category'),
    path('filter/', views.FilterMoviesView.as_view(), name='filter'),
    path('search/', views.Search.as_view(), name='search'),
    path('add-rating/', views.AddStarRating.as_view(), name='add_rating'),
    path('<slug:slug>/', views.MovieDetailView.as_view(), name='movie_detail'),
    path('review/<int:pk>/', views.AddReview.as_view(), name='add_review'),
    path('actor/<str:slug>/', views.ActorView.as_view(), name='actor_detail'),
    path('film_director/<str:slug>', views.FilmDirectorView.as_view(), name='film_director_detail'),
]

Movie_gid/movies/models.py
from django.db import models
from datetime import date
from django.urls import reverse


class Category(models.Model):
    """ Category of movies """
    name = models.CharField('Категория', max_length=150)
    description = models.TextField('Описание')
    url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Actor(models.Model):
    """ Actors of movies """
    name = models.CharField('Имя', max_length=100)
    age = models.PositiveSmallIntegerField('Возраст', default=0)
    description = models.TextField('Описание')
    image = models.ImageField('Изображение', upload_to='Actors/')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('actor_detail', kwargs={'slug': self.name})

    class Meta:
        verbose_name = 'Актеры'
        verbose_name_plural = 'Актеры'


#   Режиссеры
class FilmDirector(models.Model):
    """ Film directors of movies """
    name = models.CharField('Имя', max_length=100)
    age = models.PositiveSmallIntegerField('Возраст', default=0)
    description = models.TextField('Описание')
    image = models.ImageField('Изображение', upload_to='FilmDirectors/')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('film_director_detail', kwargs={'slug': self.name})

    class Meta:
        verbose_name = 'Режиссеры'
        verbose_name_plural = 'Режиссеры'


class Genre(models.Model):
    """ Genres of movies """
    name = models.CharField('Имя', max_length=100)
    description = models.TextField('Описание')
    url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Жанр'
        verbose_name_plural = 'Жанры'


#   Фильмы
class Movie(models.Model):
    """ Movies """
    title = models.CharField('Название', max_length=100)
    tagline = models.CharField('Слоган', max_length=100, default='')
    description = models.TextField('Описание')
    poster = models.ImageField('Постер', upload_to='movies/')
    year = models.PositiveSmallIntegerField('Дата выхода', default=2020)
    country = models.CharField('Страна', max_length=30)
    directors = models.ManyToManyField(FilmDirector, verbose_name='режиссер', related_name='film_director')
    actors = models.ManyToManyField(Actor, verbose_name='актеры', related_name='film_actor')
    genres = models.ManyToManyField(Genre, verbose_name='жанры')
    world_premiere = models.DateField('Премьера в мире', default=date.today)
    budget = models.PositiveIntegerField('Бюджет', default=0, help_text='указывать сумму в долларах')
    fees_in_usa = models.PositiveIntegerField('Сборы в США', default=0, help_text='указывать сумму в долларах')
    fees_in_world = models.PositiveIntegerField('Сборы в мире', default=0, help_text='указывать сумму в долларах')
    category = models.ForeignKey(Category, verbose_name='Категория', on_delete=models.SET_NULL, null=True)
    url = models.SlugField(max_length=130, unique=True)
    draft = models.BooleanField('Черновик', default=False)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('movie_detail', kwargs={'slug': self.url})

    def get_review(self):
        return self.reviews_set.filter(parent__isnull=True)

    class Meta:
        verbose_name = 'Фильм'
        verbose_name_plural = 'Фильмы'


#   Кадры фильмов
class MovieShots(models.Model):
    """ Shots scenes of movies """
    title = models.CharField('Заголовок', max_length=100)
    description = models.TextField('Описание')
    image = models.ImageField('Изображение', upload_to='movie_shots/')
    movie = models.ForeignKey(Movie, verbose_name='Фильм', on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Кадр из фильма'
        verbose_name_plural = 'Кадры из фильма'


class RatingStars(models.Model):
    """ Stars for view valuing of rating """
    value = models.SmallIntegerField('Значение', default=0)

    def __str__(self):
        return f'{self.value}'

    class Meta:
        verbose_name = 'Звезда рейтинга'
        verbose_name_plural = 'Звезды рейтинга'
        ordering = ['-value']


class Rating(models.Model):
    """ Add rating for movies """
    ip = models.CharField('IP адрес', max_length=15)
    star = models.ForeignKey(RatingStars, on_delete=models.CASCADE, verbose_name='звезда')
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, verbose_name='фильм')

    def __str__(self):
        return f'{self.star} - {self.movie}'

    class Meta:
        verbose_name = 'Рейтинг'
        verbose_name_plural = 'Рейтинги'


class Reviews(models.Model):
    """ Reviews of movies """
    email = models.EmailField()
    name = models.CharField('Имя', max_length=100)
    text = models.TextField('Сообщение', max_length=5000)
    parent = models.ForeignKey('self', verbose_name='Родитель', on_delete=models.SET_NULL, blank=True, null=True)
    movie = models.ForeignKey(Movie, verbose_name='фильм', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name} - {self.movie}'

    class Meta:
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'

Movie_gid/movies/forms.py
from django import forms
from snowpenguin.django.recaptcha3.fields import ReCaptchaField

from .models import Reviews, Rating, RatingStars


class ReviewForm(forms.ModelForm):
    """ Review form with fields for add review """
    captcha = ReCaptchaField()

    class Meta:
        model = Reviews
        fields = ('name', 'email', 'text', 'captcha')
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control border'}),
            'email': forms.EmailInput(attrs={'class': 'form-control border'}),
            'text': forms.Textarea(attrs={'class': 'form-control border'})
        }


#   Форма добавления рейтинга
class RatingForm(forms.ModelForm):
    """ Rating form with stars field for making rating """
    star = forms.ModelChoiceField(queryset=RatingStars.objects.all(), widget=forms.RadioSelect(), empty_label=None)

    class Meta:
        model = Rating
        fields = ('star',)

Movie_gid/movies/views.py
from django.db.models import Q
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from django.views.generic.base import View
from django.http import HttpResponse

from .models import *
from .forms import *


class GenreYear:
    """
        Object of filters for Genre, Years & Categories
    """
    def get_genres(self):
        """ Get list of genres into sidebar """
        return Genre.objects.get_queryset().order_by('id')

    def get_years(self):
        """ Get list of years into sidebar """
        return Movie.objects.filter(draft=False).values('year')

    def get_category(self):
        """ Get list of categories """
        return Category.objects.all()


class MoviesCategoryView(GenreYear, ListView):
    """ List by categories """
    paginate_by = 9

    def get_queryset(self):
        queryset = Movie.objects.filter(category__in=self.request.GET.getlist('category')).distinct()
        return queryset

    def get_context_data(self, *args, **kwargs):
        """ For with pagination urls didn't have the errors and we are can find second pages & others pages  """
        context = super().get_context_data(*args, **kwargs)
        context['category'] = ''.join([f"category={x}&" for x in self.request.GET.getlist('category')])
        return context


class MoviesView(GenreYear, ListView):
    """ List of movies on main page """
    model = Movie
    queryset = Movie.objects.filter(draft=False)
    paginate_by = 9


class MovieDetailView(GenreYear, DetailView):
    """ Movie-page, with all description """
    model = Movie
    slug_field = 'url'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['star_form'] = RatingForm()
        context['form'] = ReviewForm()
        return context


class AddReview(View):
    """ Add reviews into movie-page """
    def post(self, request, pk):
        form = ReviewForm(request.POST)
        movie = Movie.objects.get(id=pk)
        if form.is_valid():
            form = form.save(commit=False)
            #   get parent of review, for displaying in admin panel. That for we are knew, for which
            #   question belongs answer
            if request.POST.get('parent', None):
                form.parent_id = int(request.POST.get('parent'))
            form.movie = movie
            form.save()
        return redirect(movie.get_absolute_url())


class ActorView(GenreYear, DetailView):
    """ Actors information """
    model = Actor
    model_2 = FilmDirector
    template_name = 'movies/actor.html'
    slug_field = 'name'


class FilmDirectorView(GenreYear, DetailView):
    """ Film directors information """
    model = FilmDirector
    template_name = 'movies/film_director.html'
    slug_field = 'name'


class FilterMoviesView(GenreYear, ListView):
    """ Filter which displays year and genre objects in same time """
    paginate_by = 9

    def get_queryset(self):
        queryset = Movie.objects.filter(
            Q(year__in=self.request.GET.getlist('year')) |
            Q(genres__in=self.request.GET.getlist('genre'))
        ).distinct()
        return queryset

    """ For with pagination urls didn't have the errors and we are can find second pages & others pages  """
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['year'] = ''.join([f"year={x}&" for x in self.request.GET.getlist('year')])
        context['genre'] = ''.join([f"genre={x}&" for x in self.request.GET.getlist('genre')])
        return context
        

class AddStarRating(View):
    """ Add count of stars by each movie-objects """
    def get_client_ip(self, request):
        x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
        if x_forwarded_for:
            ip = x_forwarded_for.split(',')[0]
        else:
            ip = request.META.get('REMOTE_ADDR')
        return ip

    def post(self, request):
        form = RatingForm(request.POST)
        if form.is_valid():
            Rating.objects.update_or_create(
                ip=self.get_client_ip(request),
                movie_id=int(request.POST.get("movie")),
                defaults={'star_id': int(request.POST.get("star"))}
            )
            return HttpResponse(status=201)
        else:
            return HttpResponse(status=400)


class Search(ListView):
    """
        Movies search
        Note:
            SQLITE search without case sensitive just in ASCII encoding,
            Method in UTF-8 tagline__icontains - full case sensitive
        That reason limited search
    """
    paginate_by = 3

    def get_queryset(self):
        return Movie.objects.filter(title__icontains=self.request.GET.get('q'))

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['q'] = f'q={self.request.GET.get("q")}&'
        return context

Movie_gid/movies/templates/movies/actor.html
{% extends 'movies/base.html' %}
{% load static %}
{% block title %}{{ actor.name }}{% endblock title %}
{% block container %}
    <div class="container py-md-3">
{% endblock container %}

{% block sidebar %}
    <div class="side-bar col-lg-3">
{% endblock sidebar %}    

{% block movie %}
<div class="left-ads-display col-lg-8">
    <div class="row">
        <div class="col-md-6">
            <img src="{{ actor.image.url }}" class="img-fluid" alt="{{ actor.name }}" style="max-height: 400px">
        </div>
        <div class="desc1-right col-md-6 pl-lg-4">
            <h1>{{ actor.name }}</h1><hr>
            <ul>
                <li><span><b>Возраст:  </b>{{ actor.age }} лет ;</span></li>
                <li>
                    <span><b>Фильмография на сайте:</b>
                        {% for movie in actor.film_actor.all %}
                            {{ movie.title }} ;
                        {% endfor %}
                    </span>
                </li>
            </ul>
        </div>
    </div>
    <div class="row sub-para-w3layouts mt-5">

        <h3 class="shop-sing editContent">
            О {{ actor.name }}</h3>
        <p class="editContent">{{ actor.description | safe }}</p>
    </div>
</div>
{% endblock movie %}

Movie_gid/movies/templates/movies/base.html
{%	extends 'base.html' %}
{% block title %} {% endblock title %}
{% block content %}
	<section class="ab-info-main py-md-5 py-4 editContent" style="padding-left: 3rem; padding-right: 3rem;">
		{% block container %}
  	<div class="container-fluid py-md-3">
  {% endblock container %}
   <div class="row">
		  {% block sidebar %}
		   	<div class="side-bar col-lg-3">
		  {% endblock sidebar %}	
				{% include 'include/sidebar.html' %}
			</div>
				{% block movie %}
				{% endblock movie %}				
			</div>
		</div>
	</section>
{% endblock content %}

Movie_gid/movies/templates/movies/film_director.html
{% extends 'movies/base.html' %}
{% load static %}
{% block title %}{{ filmdirector.name }}{% endblock title %}
{% block container %}
    <div class="container py-md-3">
{% endblock container %}

{% block sidebar %}
    <div class="side-bar col-lg-3">
{% endblock sidebar %}    

{% block movie %}
<div class="left-ads-display col-lg-8">
    <div class="row">
        <div class="col-md-6">
            <img src="{{ filmdirector.image.url }}" class="img-fluid" alt="{{ filmdirector.name }}" style="max-height: 400px">
        </div>
        <div class="desc1-right col-md-6 pl-lg-4">
            <h1>{{ filmdirector.name }}</h1><hr>
            <ul>
                <li><span><b>Возраст:  </b>{{ filmdirector.age }} лет ;</span></li>
                <li>
                    <span><b>Режиссер:    </b>
                        {% for movie in filmdirector.film_director.all %}
                            {{ movie.title }} ;
                        {% endfor %}                
                    </span>
                </li>
            </ul>
        </div>
    </div>
    <div class="row sub-para-w3layouts mt-5">

        <h3 class="shop-sing editContent">
            О {{ filmdirector.name }}</h3>
        <p class="editContent">{{ filmdirector.description | safe }}</p>
    </div>
</div>
{% endblock movie %}

Movie_gid/movies/templates/movies/movie_category_list.html
{% extends 'movies/base.html' %}
{% block header %} bg1 {% endblock header %}
{% block movie %}
<!-- product right -->
<div class="left-ads-display col-lg-9">
    <div class="row">
        {% for movie in category %}
            <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12" id="block-card">
                <div class="text-center mt-lg-4 mb-3" id="card-of-movies">
                    <div class="men-thumb-item">
                        <a href="{{ movie.get_absolute_url }}" class="editContent" ><img src="{{ movie.poster.url }}" class="img-fluid" alt="" ></a>
                    </div>
                    <div class="item-info-product">
                        <h4>
                            <a href="{{ movie.get_absolute_url }}" class="editContent" >{{ movie.title }}</a>
                        </h4>

                        <div class="product_price">
                            <div class="grid-price">
                                    <p class="tagline_block" >{{ movie.tagline }}</p> 
                                <hr>
                                <p>Год: {{ movie.year }}</p><hr>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
        <div class="grid-img-right mt-4 text-right bg bg1" >
            {% include 'include/pagination.html' %}
        </div>
</div>    
<!-- //contact -->
{% endblock movie %}

Movie_gid/movies/templates/movies/movie_detail.html
{% extends 'movies/base.html' %}
{% load static %}
{% block title %}{{ movie.title }}{% endblock title %}
{% block container %}
    <div class="container py-md-3">
{% endblock container %}

{% block sidebar %}
    <div class="side-bar col-lg-4">
{% endblock sidebar %}    

{% block movie %}
<div class="left-ads-display col-lg-8">
    <div class="row">
        <div class="col-md-6">
            <img src="{{ movie.poster.url }}" class="img-fluid" alt="">
        </div>
        <div class="desc1-right col-md-6 pl-lg-4">
            <h1 class="editContent" style="outline: none; cursor: inherit;">{{ movie.title }}</h1>
            <h5 class="editContent"></h5>
            <ul>
                <li style="list-style: none"><span><b>Год:  </b>{{ movie.year }} ;</span></li>
                <li style="list-style: none"><span><b>Страна:   </b>{{ movie.country }} ;</span>
                </li>
                <li style="list-style: none"><span><b>Слоган:   </b>{{ movie.tagline }} ;</span>
                </li>
                <li style="list-style: none">
                    <span><b>Режиссер:  </b>
                        {% for director in movie.directors.all %}
                            <a href="{{ director.get_absolute_url }}">
                                {{ director.name }} ;    
                            </a>
                        {% endfor %}
                    </span>
                </li>
                <li style="list-style: none">
                    <span><b>Актеры:    </b>
                        {% for actor in movie.actors.all %}
                            {% if actor.name %}
                                <a href="{{ actor.get_absolute_url }}">
                                    {{ actor.name }},
                                </a>
                            {% else %}
                                <p>;</p>
                            {% endif %}
                        {% endfor %}
                    </span>
                </li>
                <li style="list-style: none">
                    <span><b>Жанр:  </b>
                        {% for genre in movie.genres.all %}
                            {{ genre.name }} ;
                        {% endfor %}
                    </span>
                </li>
                <li style="list-style: none"><span><b>Премьера в мире:</b>{{ movie.world_premiere }} ;</span>
                </li>
                <li style="list-style: none">
                    <span><b>Бюджет:    </b>${{ movie.budget }} ;</span></li>
                <li style="list-style: none">
                    <span><b>Сборы в США:   </b>${{ movie.fees_in_usa }} ;</span></li>
                <li style="list-style: none"><span><b>Сборы в мире: </b>${{ movie.fees_in_world }} ;</span>
                </li>
                    <form action="{% url 'add_rating' %}" method="post" name="rating">
                        <b>Рейтинг:</b>
                        {% csrf_token %}
                        <input type="hidden" value="{{ movie.id }}" name="movie">
                        <span class="rating">
                            {% for k, v in star_form.fields.star.choices %}
                                <input id="rating{{ v }}" type="radio" name="star" value="{{ k }}">
                            <label for="rating{{ v }}">{{ k }}</label>
                            {% endfor %}
                        </span>
                        <span class="editContent">4.0</span>
                    </form>
                </li>
            </ul>
            
                <div class="share-desc">
                    <div class="share">
                        <h4 class="editContent"
                            style="outline: none; cursor: inherit;">
                            Share:</h4>
                        <ul class="w3layouts_social_list list-unstyled">
                            <li>
                                <a href="#" class="w3pvt_facebook editContent"
                                   style="outline: none; cursor: inherit;">
                                <span class="fa fa-facebook-f"
                                      style="outline: none; cursor: inherit;"></span>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="w3pvt_twitter editContent"
                                   style="outline: none; cursor: inherit;">
                                <span class="fa fa-twitter"
                                      style="outline: none; cursor: inherit;"></span>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="w3pvt_dribble editContent"
                                   style="outline: none; cursor: inherit;">
                                <span class="fa fa-dribbble"
                                      style="outline: none; cursor: inherit;"></span>
                                </a>
                            </li>
                        </ul>
                    </div>
                    <div class="clearfix"></div>
                </div>
        </div>
    </div>
    <div class="row sub-para-w3layouts mt-5">

        <h3 class="shop-sing editContent" style="outline: none; cursor: inherit;">
            О фильме {{ movie.title }}</h3>
        <p>
            {% for image in movie.movieshots_set.all %}
                <img src="{{ image.image.url }}" class="img-movie-shots" alt="{{ image.description }}">
            {% endfor %}
        </p>
        <p class="editContent" style="outline: none; cursor: inherit;">{{ movie.description | safe }}</p>
    </div>
    <hr>
    <div class="row">
        <div class="single-form-left col-lg-12">
            {% if user.is_authenticated %}
                <!-- contact form grid -->
                <div class="contact-single">
                    <h3 class="editContent" style="outline: none; cursor: inherit;">
                        <span class="sub-tittle editContent" style="outline: none; cursor: inherit;">Количество отзывов: {{ movie.reviews_set.count }}</span>Оставить отзыв</h3>
                    <form action="{% url 'add_review' movie.id %}" method="post" class="mt-4" id="formReview">
                        {% csrf_token %}
                        <input type="hidden" name="parent" id="contactparent" value="">
                        <div class="form-group editContent"
                             style="outline: none; cursor: inherit;">
                            <label for="contactcomment" class="editContent">
                                Ваш комментарий*
                            </label>
                            {{ form.text }}
                        </div>
                        <div class="d-sm-flex">
                            <div class="col-sm-6 form-group p-0 editContent"
                                 >
                                <label for="contactusername" class="editContent">
                                    Имя*
                                </label>
                                {{ form.name }}
                            </div>
                            <div class="col-sm-6 form-group ml-sm-3 editContent"
                                 >
                                <label for="contactemail" class="editContent">
                                    Email*
                                </label>
                                {{ form.email }}
                            </div>
                            {{ form.captcha }}
                        </div>
                        <button type="submit" class="mt-3 btn btn-success btn-block py-3">
                            Отправить
                        </button>
                    </form>
                </div>
            {% else %}
                <span><a href="{% url 'account_login' %}">Войдите</a> в аккаунт или <a href="{% url 'account_signup' %}">зарегистрируйтесь</a>, чтобы оставлять коментарии</span>
            {% endif %}
            <!--  //contact form grid ends here -->
        </div>
    {% for review in movie.get_review %}
        <div class="media py-5 col-lg-12">
            <img src="{% static 'images/default.png' %}" class="mr-3 img-review" alt="image">
            <div class="media-body mt-4">
                <h5 class="mt-0 editContent">
                    {{ review.name }}
                </h5>
                <p class="mt-2 editContent">
                    {{ review.text }}
                </p>
                <a href="#formReview" onclick="addReview('{{ review.name }}', '{{ review.id }}')">Ответить</a>
                {% for rew in review.reviews_set.all %}
                <div class="media mt-5 editContent">
                    <a class="pr-3" href="#">
                        <img src="{% static 'images/default.png' %}" class="mr-3 img-review">
                    </a>
                    <div class="media-body">
                        <h5 class="mt-0 editContent">{{ rew.name }}</h5>
                        <p class="mt-2 editContent">{{ rew.text }}</p>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    {% endfor %}
    </div>
</div>
<script>
    function addReview(name, id) {
        document.getElementById("contactparent").value = id;
        document.getElementById("contactcomment").innerText = `${name}, `
    }
</script>
{% endblock movie %}

Movie_gid/movies/templates/movies/movie_list.html
{% extends 'movies/base.html' %}
{% block header %} bg1 {% endblock header %}
{% block movie %}
<!-- product right -->
<div class="left-ads-display col-lg-9">
    <div class="row">
        {% for movie in movie_list %}
            <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12" id="block-card">
                <div class="text-center mt-lg-4 mb-3" id="card-of-movies">
                    <div class="men-thumb-item">
                        <a href="{{ movie.get_absolute_url }}" class="editContent" ><img src="{{ movie.poster.url }}" class="img-fluid" alt="" ></a>
                    </div>
                    <div class="item-info-product">
                        <h4>
                            <a href="{{ movie.get_absolute_url }}" class="editContent" >{{ movie.title }}</a>
                        </h4>

                        <div class="product_price">
                            <div class="grid-price">
                                    <p class="tagline_block" >{{ movie.tagline }}</p> 
                                <hr>
                                <p>Год: {{ movie.year }}</p><hr>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
        <div class="grid-img-right mt-4 text-right bg bg1" >
            {% include 'include/pagination.html' %}
        </div>
</div>    
<!-- //contact -->
{% endblock movie %}